# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(758, 572)
        self.text_window = QtGui.QTextEdit(Dialog)
        self.text_window.setGeometry(QtCore.QRect(40, 360, 681, 191))
        self.text_window.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text_window.setObjectName(_fromUtf8("text_window"))
        self.clusterWidget = QtGui.QTabWidget(Dialog)
        self.clusterWidget.setGeometry(QtCore.QRect(40, 20, 241, 231))
        self.clusterWidget.setObjectName(_fromUtf8("clusterWidget"))
        self.kmeans_tab = QtGui.QWidget()
        self.kmeans_tab.setObjectName(_fromUtf8("kmeans_tab"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.kmeans_tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.kmeans_iters_line = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.kmeans_iters_line.setObjectName(_fromUtf8("kmeans_iters_line"))
        self.horizontalLayout_3.addWidget(self.kmeans_iters_line)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.kmeans_tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 211, 71))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.kmeans_times_line = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.kmeans_times_line.setObjectName(_fromUtf8("kmeans_times_line"))
        self.horizontalLayout_4.addWidget(self.kmeans_times_line)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.kmeans_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 80, 211, 71))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.kmeans_k_line = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.kmeans_k_line.setObjectName(_fromUtf8("kmeans_k_line"))
        self.horizontalLayout_5.addWidget(self.kmeans_k_line)
        self.kmeansbutton = QtGui.QPushButton(self.kmeans_tab)
        self.kmeansbutton.setGeometry(QtCore.QRect(130, 160, 91, 31))
        self.kmeansbutton.setObjectName(_fromUtf8("kmeansbutton"))
        self.clusterWidget.addTab(self.kmeans_tab, _fromUtf8(""))
        self.hierarch_tab = QtGui.QWidget()
        self.hierarch_tab.setObjectName(_fromUtf8("hierarch_tab"))
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.hierarch_tab)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.hier_maxd_line = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.hier_maxd_line.setObjectName(_fromUtf8("hier_maxd_line"))
        self.horizontalLayout_7.addWidget(self.hier_maxd_line)
        self.horizontalLayoutWidget_9 = QtGui.QWidget(self.hierarch_tab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 40, 211, 71))
        self.horizontalLayoutWidget_9.setObjectName(_fromUtf8("horizontalLayoutWidget_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget_9)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.hier_linkage_box = QtGui.QComboBox(self.horizontalLayoutWidget_9)
        self.hier_linkage_box.setObjectName(_fromUtf8("hier_linkage_box"))
        self.hier_linkage_box.addItem(_fromUtf8(""))
        self.hier_linkage_box.addItem(_fromUtf8(""))
        self.hier_linkage_box.addItem(_fromUtf8(""))
        self.hier_linkage_box.addItem(_fromUtf8(""))
        self.hier_linkage_box.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.hier_linkage_box)
        self.hierarbutton = QtGui.QPushButton(self.hierarch_tab)
        self.hierarbutton.setGeometry(QtCore.QRect(130, 160, 91, 31))
        self.hierarbutton.setObjectName(_fromUtf8("hierarbutton"))
        self.clusterWidget.addTab(self.hierarch_tab, _fromUtf8(""))
        self.dbscan_tab = QtGui.QWidget()
        self.dbscan_tab.setObjectName(_fromUtf8("dbscan_tab"))
        self.horizontalLayoutWidget_10 = QtGui.QWidget(self.dbscan_tab)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_10.setObjectName(_fromUtf8("horizontalLayoutWidget_10"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget_10)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.dbscan_eps_line = QtGui.QLineEdit(self.horizontalLayoutWidget_10)
        self.dbscan_eps_line.setObjectName(_fromUtf8("dbscan_eps_line"))
        self.horizontalLayout_9.addWidget(self.dbscan_eps_line)
        self.horizontalLayoutWidget_11 = QtGui.QWidget(self.dbscan_tab)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 40, 211, 71))
        self.horizontalLayoutWidget_11.setObjectName(_fromUtf8("horizontalLayoutWidget_11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget_11)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        spacerItem5 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.dbscan_minpts_line = QtGui.QLineEdit(self.horizontalLayoutWidget_11)
        self.dbscan_minpts_line.setObjectName(_fromUtf8("dbscan_minpts_line"))
        self.horizontalLayout_10.addWidget(self.dbscan_minpts_line)
        self.dbscanbutton = QtGui.QPushButton(self.dbscan_tab)
        self.dbscanbutton.setGeometry(QtCore.QRect(130, 160, 91, 31))
        self.dbscanbutton.setObjectName(_fromUtf8("dbscanbutton"))
        self.clusterWidget.addTab(self.dbscan_tab, _fromUtf8(""))
        self.validateWidget = QtGui.QTabWidget(Dialog)
        self.validateWidget.setGeometry(QtCore.QRect(300, 20, 241, 231))
        self.validateWidget.setObjectName(_fromUtf8("validateWidget"))
        self.knn_tab = QtGui.QWidget()
        self.knn_tab.setObjectName(_fromUtf8("knn_tab"))
        self.horizontalLayoutWidget_12 = QtGui.QWidget(self.knn_tab)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_12.setObjectName(_fromUtf8("horizontalLayoutWidget_12"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_12)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        spacerItem6 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.knn_n_line = QtGui.QLineEdit(self.horizontalLayoutWidget_12)
        self.knn_n_line.setObjectName(_fromUtf8("knn_n_line"))
        self.horizontalLayout_11.addWidget(self.knn_n_line)
        self.horizontalLayoutWidget_13 = QtGui.QWidget(self.knn_tab)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 40, 211, 71))
        self.horizontalLayoutWidget_13.setObjectName(_fromUtf8("horizontalLayoutWidget_13"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_13)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_12.addWidget(self.label_13)
        spacerItem7 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.knn_perc_line = QtGui.QLineEdit(self.horizontalLayoutWidget_13)
        self.knn_perc_line.setObjectName(_fromUtf8("knn_perc_line"))
        self.horizontalLayout_12.addWidget(self.knn_perc_line)
        self.knnbutton = QtGui.QPushButton(self.knn_tab)
        self.knnbutton.setGeometry(QtCore.QRect(120, 150, 101, 41))
        self.knnbutton.setObjectName(_fromUtf8("knnbutton"))
        self.validateWidget.addTab(self.knn_tab, _fromUtf8(""))
        self.svm_tab = QtGui.QWidget()
        self.svm_tab.setObjectName(_fromUtf8("svm_tab"))
        self.horizontalLayoutWidget_14 = QtGui.QWidget(self.svm_tab)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_14.setObjectName(_fromUtf8("horizontalLayoutWidget_14"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_14)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_13.addWidget(self.label_14)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.svm_kernel_box = QtGui.QComboBox(self.horizontalLayoutWidget_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.svm_kernel_box.sizePolicy().hasHeightForWidth())
        self.svm_kernel_box.setSizePolicy(sizePolicy)
        self.svm_kernel_box.setObjectName(_fromUtf8("svm_kernel_box"))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.svm_kernel_box)
        self.svm_button = QtGui.QPushButton(self.svm_tab)
        self.svm_button.setGeometry(QtCore.QRect(130, 160, 91, 31))
        self.svm_button.setObjectName(_fromUtf8("svm_button"))
        self.horizontalLayoutWidget_16 = QtGui.QWidget(self.svm_tab)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(10, 80, 211, 71))
        self.horizontalLayoutWidget_16.setObjectName(_fromUtf8("horizontalLayoutWidget_16"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_16)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        spacerItem9 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem9)
        self.svm_r_line = QtGui.QLineEdit(self.horizontalLayoutWidget_16)
        self.svm_r_line.setObjectName(_fromUtf8("svm_r_line"))
        self.horizontalLayout_15.addWidget(self.svm_r_line)
        spacerItem10 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem10)
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_16)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.svm_deg_line = QtGui.QLineEdit(self.horizontalLayoutWidget_16)
        self.svm_deg_line.setObjectName(_fromUtf8("svm_deg_line"))
        self.horizontalLayout_15.addWidget(self.svm_deg_line)
        self.label = QtGui.QLabel(self.svm_tab)
        self.label.setGeometry(QtCore.QRect(10, 130, 111, 41))
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayoutWidget_17 = QtGui.QWidget(self.svm_tab)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 40, 211, 71))
        self.horizontalLayoutWidget_17.setObjectName(_fromUtf8("horizontalLayoutWidget_17"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_16.addWidget(self.label_19)
        spacerItem11 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.svm_gamma_line = QtGui.QLineEdit(self.horizontalLayoutWidget_17)
        self.svm_gamma_line.setObjectName(_fromUtf8("svm_gamma_line"))
        self.horizontalLayout_16.addWidget(self.svm_gamma_line)
        self.svm_perc_line = QtGui.QLineEdit(self.svm_tab)
        self.svm_perc_line.setGeometry(QtCore.QRect(10, 160, 81, 20))
        self.svm_perc_line.setObjectName(_fromUtf8("svm_perc_line"))
        self.validateWidget.addTab(self.svm_tab, _fromUtf8(""))
        self.years_tag = QtGui.QTabWidget(Dialog)
        self.years_tag.setEnabled(True)
        self.years_tag.setGeometry(QtCore.QRect(560, 20, 161, 231))
        self.years_tag.setObjectName(_fromUtf8("years_tag"))
        self.train_years_tab = QtGui.QWidget()
        self.train_years_tab.setObjectName(_fromUtf8("train_years_tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.train_years_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 160, 201))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.years_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.years_layout.setObjectName(_fromUtf8("years_layout"))
        self.check2002 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2002.setObjectName(_fromUtf8("check2002"))
        self.years_layout.addWidget(self.check2002, 0, 0, 1, 1)
        self.check2003 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2003.setObjectName(_fromUtf8("check2003"))
        self.years_layout.addWidget(self.check2003, 1, 0, 1, 1)
        self.check2004 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2004.setObjectName(_fromUtf8("check2004"))
        self.years_layout.addWidget(self.check2004, 2, 0, 1, 1)
        self.check2005 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2005.setObjectName(_fromUtf8("check2005"))
        self.years_layout.addWidget(self.check2005, 3, 0, 1, 1)
        self.check2006 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2006.setObjectName(_fromUtf8("check2006"))
        self.years_layout.addWidget(self.check2006, 4, 0, 1, 1)
        self.check2007 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2007.setObjectName(_fromUtf8("check2007"))
        self.years_layout.addWidget(self.check2007, 5, 0, 1, 1)
        self.check2008 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2008.setObjectName(_fromUtf8("check2008"))
        self.years_layout.addWidget(self.check2008, 6, 0, 1, 1)
        self.check2009 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2009.setObjectName(_fromUtf8("check2009"))
        self.years_layout.addWidget(self.check2009, 7, 0, 1, 1)
        self.check2011 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2011.setObjectName(_fromUtf8("check2011"))
        self.years_layout.addWidget(self.check2011, 1, 1, 1, 1)
        self.check2010 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2010.setObjectName(_fromUtf8("check2010"))
        self.years_layout.addWidget(self.check2010, 0, 1, 1, 1)
        self.check2012 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2012.setObjectName(_fromUtf8("check2012"))
        self.years_layout.addWidget(self.check2012, 2, 1, 1, 1)
        self.check2013 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2013.setObjectName(_fromUtf8("check2013"))
        self.years_layout.addWidget(self.check2013, 3, 1, 1, 1)
        self.check2014 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2014.setObjectName(_fromUtf8("check2014"))
        self.years_layout.addWidget(self.check2014, 4, 1, 1, 1)
        self.check2015 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2015.setObjectName(_fromUtf8("check2015"))
        self.years_layout.addWidget(self.check2015, 5, 1, 1, 1)
        self.check2016 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2016.setObjectName(_fromUtf8("check2016"))
        self.years_layout.addWidget(self.check2016, 6, 1, 1, 1)
        self.checkAllbutton = QtGui.QPushButton(self.gridLayoutWidget)
        self.checkAllbutton.setObjectName(_fromUtf8("checkAllbutton"))
        self.years_layout.addWidget(self.checkAllbutton, 7, 1, 1, 1)
        self.years_tag.addTab(self.train_years_tab, _fromUtf8(""))
        self.PCA_label = QtGui.QLabel(Dialog)
        self.PCA_label.setGeometry(QtCore.QRect(40, 270, 201, 16))
        self.PCA_label.setObjectName(_fromUtf8("PCA_label"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 260, 160, 80))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.pca_box_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.pca_box_layout.setObjectName(_fromUtf8("pca_box_layout"))
        self.pca_box = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.pca_box.setObjectName(_fromUtf8("pca_box"))
        self.pca_box_layout.addWidget(self.pca_box)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 260, 235, 78))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.pca_data_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.pca_data_layout.setObjectName(_fromUtf8("pca_data_layout"))
        self.dimension_layout = QtGui.QHBoxLayout()
        self.dimension_layout.setObjectName(_fromUtf8("dimension_layout"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.dimension_layout.addWidget(self.label_2)
        self.dimension_edit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.dimension_edit.setObjectName(_fromUtf8("dimension_edit"))
        self.dimension_layout.addWidget(self.dimension_edit)
        self.pca_data_layout.addLayout(self.dimension_layout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.threshold_edit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.threshold_edit_2.setText(_fromUtf8(""))
        self.threshold_edit_2.setObjectName(_fromUtf8("threshold_edit_2"))
        self.horizontalLayout.addWidget(self.threshold_edit_2)
        self.pca_data_layout.addLayout(self.horizontalLayout)
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(599, 281, 121, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Dialog)
        self.clusterWidget.setCurrentIndex(0)
        self.validateWidget.setCurrentIndex(0)
        self.years_tag.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_3.setText(_translate("Dialog", "Executions", None))
        self.kmeans_iters_line.setText(_translate("Dialog", "100", None))
        self.label_5.setText(_translate("Dialog", "Iterations", None))
        self.kmeans_times_line.setText(_translate("Dialog", "6", None))
        self.label_6.setText(_translate("Dialog", "No. of clusters", None))
        self.kmeans_k_line.setText(_translate("Dialog", "4", None))
        self.kmeansbutton.setText(_translate("Dialog", "Clusterize", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.kmeans_tab), _translate("Dialog", "K-means", None))
        self.label_8.setText(_translate("Dialog", "Max distance", None))
        self.hier_maxd_line.setText(_translate("Dialog", "150", None))
        self.label_9.setText(_translate("Dialog", "Linkage criteria", None))
        self.hier_linkage_box.setItemText(0, _translate("Dialog", "ward", None))
        self.hier_linkage_box.setItemText(1, _translate("Dialog", "single", None))
        self.hier_linkage_box.setItemText(2, _translate("Dialog", "complete", None))
        self.hier_linkage_box.setItemText(3, _translate("Dialog", "average", None))
        self.hier_linkage_box.setItemText(4, _translate("Dialog", "weighted", None))
        self.hierarbutton.setText(_translate("Dialog", "Clusterize", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.hierarch_tab), _translate("Dialog", "Hierarchical", None))
        self.label_10.setText(_translate("Dialog", "Epsilon", None))
        self.dbscan_eps_line.setText(_translate("Dialog", "0.004", None))
        self.label_11.setText(_translate("Dialog", "Min_Pts", None))
        self.dbscan_minpts_line.setText(_translate("Dialog", "2692", None))
        self.dbscanbutton.setText(_translate("Dialog", "Clusterize", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.dbscan_tab), _translate("Dialog", "DBSCAN", None))
        self.label_12.setText(_translate("Dialog", "No. of neighbors", None))
        self.knn_n_line.setText(_translate("Dialog", "4", None))
        self.label_13.setText(_translate("Dialog", "% of sets for training", None))
        self.knn_perc_line.setText(_translate("Dialog", "80", None))
        self.knnbutton.setText(_translate("Dialog", "Train set \n"
" and validate", None))
        self.validateWidget.setTabText(self.validateWidget.indexOf(self.knn_tab), _translate("Dialog", "K-nn", None))
        self.label_14.setText(_translate("Dialog", "Kernel", None))
        self.svm_kernel_box.setItemText(0, _translate("Dialog", "rbf", None))
        self.svm_kernel_box.setItemText(1, _translate("Dialog", "linear", None))
        self.svm_kernel_box.setItemText(2, _translate("Dialog", "poli", None))
        self.svm_kernel_box.setItemText(3, _translate("Dialog", "sigmoid", None))
        self.svm_button.setText(_translate("Dialog", "Train set \n"
" and validate", None))
        self.label_16.setText(_translate("Dialog", "r", None))
        self.svm_r_line.setText(_translate("Dialog", "0.0", None))
        self.label_17.setText(_translate("Dialog", "degree", None))
        self.svm_deg_line.setText(_translate("Dialog", "3", None))
        self.label.setText(_translate("Dialog", "% of sets for training", None))
        self.label_19.setText(_translate("Dialog", "gamma", None))
        self.svm_gamma_line.setText(_translate("Dialog", "0.125", None))
        self.svm_perc_line.setText(_translate("Dialog", "80", None))
        self.validateWidget.setTabText(self.validateWidget.indexOf(self.svm_tab), _translate("Dialog", "SVM", None))
        self.check2002.setText(_translate("Dialog", "~2002", None))
        self.check2003.setText(_translate("Dialog", "2003", None))
        self.check2004.setText(_translate("Dialog", "2004", None))
        self.check2005.setText(_translate("Dialog", "2005", None))
        self.check2006.setText(_translate("Dialog", "2006", None))
        self.check2007.setText(_translate("Dialog", "2007", None))
        self.check2008.setText(_translate("Dialog", "2008", None))
        self.check2009.setText(_translate("Dialog", "2009", None))
        self.check2011.setText(_translate("Dialog", "2011", None))
        self.check2010.setText(_translate("Dialog", "2010", None))
        self.check2012.setText(_translate("Dialog", "2012", None))
        self.check2013.setText(_translate("Dialog", "2013", None))
        self.check2014.setText(_translate("Dialog", "2014", None))
        self.check2015.setText(_translate("Dialog", "2015", None))
        self.check2016.setText(_translate("Dialog", "2016", None))
        self.checkAllbutton.setText(_translate("Dialog", "Check all", None))
        self.years_tag.setTabText(self.years_tag.indexOf(self.train_years_tab), _translate("Dialog", "Train years", None))
        self.PCA_label.setText(_translate("Dialog", "Principal Component Analysis", None))
        self.pca_box.setText(_translate("Dialog", "Use PCA", None))
        self.label_2.setText(_translate("Dialog", "Dimension:", None))
        self.label_4.setText(_translate("Dialog", "Threshold:", None))
        self.pushButton.setText(_translate("Dialog", "Update selected\n"
"dictionaries", None))

