# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(821, 572)
        self.text_window = QtGui.QTextEdit(Dialog)
        self.text_window.setGeometry(QtCore.QRect(40, 360, 741, 191))
        self.text_window.setObjectName(_fromUtf8("text_window"))
        self.clusterWidget = QtGui.QTabWidget(Dialog)
        self.clusterWidget.setGeometry(QtCore.QRect(40, 20, 261, 231))
        self.clusterWidget.setObjectName(_fromUtf8("clusterWidget"))
        self.kmeans_tab = QtGui.QWidget()
        self.kmeans_tab.setObjectName(_fromUtf8("kmeans_tab"))
        self.clusterWidget.addTab(self.kmeans_tab, _fromUtf8(""))
        self.hierarch_tab = QtGui.QWidget()
        self.hierarch_tab.setObjectName(_fromUtf8("hierarch_tab"))
        self.clusterWidget.addTab(self.hierarch_tab, _fromUtf8(""))
        self.dbscan_tab = QtGui.QWidget()
        self.dbscan_tab.setObjectName(_fromUtf8("dbscan_tab"))
        self.clusterWidget.addTab(self.dbscan_tab, _fromUtf8(""))
        self.validateWidget = QtGui.QTabWidget(Dialog)
        self.validateWidget.setGeometry(QtCore.QRect(330, 20, 261, 231))
        self.validateWidget.setObjectName(_fromUtf8("validateWidget"))
        self.knn_tab = QtGui.QWidget()
        self.knn_tab.setObjectName(_fromUtf8("knn_tab"))
        self.validateWidget.addTab(self.knn_tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.validateWidget.addTab(self.tab_3, _fromUtf8(""))
        self.years_tag = QtGui.QTabWidget(Dialog)
        self.years_tag.setEnabled(True)
        self.years_tag.setGeometry(QtCore.QRect(620, 20, 161, 231))
        self.years_tag.setObjectName(_fromUtf8("years_tag"))
        self.train_years_tab = QtGui.QWidget()
        self.train_years_tab.setObjectName(_fromUtf8("train_years_tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.train_years_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 151, 201))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.years_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.years_layout.setObjectName(_fromUtf8("years_layout"))
        self.check2002 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2002.setObjectName(_fromUtf8("check2002"))
        self.years_layout.addWidget(self.check2002, 0, 0, 1, 1)
        self.check2003 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2003.setObjectName(_fromUtf8("check2003"))
        self.years_layout.addWidget(self.check2003, 1, 0, 1, 1)
        self.check2004 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2004.setObjectName(_fromUtf8("check2004"))
        self.years_layout.addWidget(self.check2004, 2, 0, 1, 1)
        self.check2005 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2005.setObjectName(_fromUtf8("check2005"))
        self.years_layout.addWidget(self.check2005, 3, 0, 1, 1)
        self.check2006 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2006.setObjectName(_fromUtf8("check2006"))
        self.years_layout.addWidget(self.check2006, 4, 0, 1, 1)
        self.check2007 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2007.setObjectName(_fromUtf8("check2007"))
        self.years_layout.addWidget(self.check2007, 5, 0, 1, 1)
        self.check2008 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2008.setObjectName(_fromUtf8("check2008"))
        self.years_layout.addWidget(self.check2008, 6, 0, 1, 1)
        self.check2009 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2009.setObjectName(_fromUtf8("check2009"))
        self.years_layout.addWidget(self.check2009, 7, 0, 1, 1)
        self.check2011 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2011.setObjectName(_fromUtf8("check2011"))
        self.years_layout.addWidget(self.check2011, 1, 1, 1, 1)
        self.check2010 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2010.setObjectName(_fromUtf8("check2010"))
        self.years_layout.addWidget(self.check2010, 0, 1, 1, 1)
        self.check2012 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2012.setObjectName(_fromUtf8("check2012"))
        self.years_layout.addWidget(self.check2012, 2, 1, 1, 1)
        self.check2013 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2013.setObjectName(_fromUtf8("check2013"))
        self.years_layout.addWidget(self.check2013, 3, 1, 1, 1)
        self.check2014 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2014.setObjectName(_fromUtf8("check2014"))
        self.years_layout.addWidget(self.check2014, 4, 1, 1, 1)
        self.check2015 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2015.setObjectName(_fromUtf8("check2015"))
        self.years_layout.addWidget(self.check2015, 5, 1, 1, 1)
        self.check2016 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2016.setObjectName(_fromUtf8("check2016"))
        self.years_layout.addWidget(self.check2016, 6, 1, 1, 1)
        self.years_tag.addTab(self.train_years_tab, _fromUtf8(""))
        self.PCA_label = QtGui.QLabel(Dialog)
        self.PCA_label.setGeometry(QtCore.QRect(40, 270, 201, 16))
        self.PCA_label.setObjectName(_fromUtf8("PCA_label"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 260, 160, 80))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.pca_box_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.pca_box_layout.setObjectName(_fromUtf8("pca_box_layout"))
        self.pca_box = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.pca_box.setObjectName(_fromUtf8("pca_box"))
        self.pca_box_layout.addWidget(self.pca_box)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 260, 235, 78))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.pca_data_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.pca_data_layout.setObjectName(_fromUtf8("pca_data_layout"))
        self.dimension_layout = QtGui.QHBoxLayout()
        self.dimension_layout.setObjectName(_fromUtf8("dimension_layout"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.dimension_layout.addWidget(self.label_2)
        self.dimension_edit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.dimension_edit.setObjectName(_fromUtf8("dimension_edit"))
        self.dimension_layout.addWidget(self.dimension_edit)
        self.pca_data_layout.addLayout(self.dimension_layout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.threshold_edit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.threshold_edit_2.setObjectName(_fromUtf8("threshold_edit_2"))
        self.horizontalLayout.addWidget(self.threshold_edit_2)
        self.pca_data_layout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.clusterWidget.setCurrentIndex(2)
        self.validateWidget.setCurrentIndex(1)
        self.years_tag.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.kmeans_tab), _translate("Dialog", "K-means", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.hierarch_tab), _translate("Dialog", "Hierarchical", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.dbscan_tab), _translate("Dialog", "DBSCAN", None))
        self.validateWidget.setTabText(self.validateWidget.indexOf(self.knn_tab), _translate("Dialog", "K-nn", None))
        self.validateWidget.setTabText(self.validateWidget.indexOf(self.tab_3), _translate("Dialog", "SVM", None))
        self.check2002.setText(_translate("Dialog", "~2002", None))
        self.check2003.setText(_translate("Dialog", "2003", None))
        self.check2004.setText(_translate("Dialog", "2004", None))
        self.check2005.setText(_translate("Dialog", "2005", None))
        self.check2006.setText(_translate("Dialog", "2006", None))
        self.check2007.setText(_translate("Dialog", "2007", None))
        self.check2008.setText(_translate("Dialog", "2008", None))
        self.check2009.setText(_translate("Dialog", "2009", None))
        self.check2011.setText(_translate("Dialog", "2011", None))
        self.check2010.setText(_translate("Dialog", "2010", None))
        self.check2012.setText(_translate("Dialog", "2012", None))
        self.check2013.setText(_translate("Dialog", "2013", None))
        self.check2014.setText(_translate("Dialog", "2014", None))
        self.check2015.setText(_translate("Dialog", "2015", None))
        self.check2016.setText(_translate("Dialog", "2016", None))
        self.years_tag.setTabText(self.years_tag.indexOf(self.train_years_tab), _translate("Dialog", "Train years", None))
        self.PCA_label.setText(_translate("Dialog", "Principal Component Analysis", None))
        self.pca_box.setText(_translate("Dialog", "Use PCA", None))
        self.label_2.setText(_translate("Dialog", "Dimension:", None))
        self.label_4.setText(_translate("Dialog", "Threshold:", None))

