# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_test_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TFG(object):
    def setupUi(self, TFG):
        TFG.setObjectName(_fromUtf8("TFG"))
        TFG.resize(1110, 463)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TFG.sizePolicy().hasHeightForWidth())
        TFG.setSizePolicy(sizePolicy)
        self.text_window = QtGui.QTextEdit(TFG)
        self.text_window.setGeometry(QtCore.QRect(760, 20, 321, 421))
        self.text_window.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.text_window.setObjectName(_fromUtf8("text_window"))
        self.clusterWidget = QtGui.QTabWidget(TFG)
        self.clusterWidget.setGeometry(QtCore.QRect(20, 20, 281, 381))
        self.clusterWidget.setObjectName(_fromUtf8("clusterWidget"))
        self.input_tab = QtGui.QWidget()
        self.input_tab.setObjectName(_fromUtf8("input_tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.input_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 271, 351))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fileLoad_button = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.fileLoad_button.setChecked(True)
        self.fileLoad_button.setObjectName(_fromUtf8("fileLoad_button"))
        self.horizontalLayout_2.addWidget(self.fileLoad_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.filename_edit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.filename_edit.setObjectName(_fromUtf8("filename_edit"))
        self.horizontalLayout_2.addWidget(self.filename_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLoad_button = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.formLoad_button.setObjectName(_fromUtf8("formLoad_button"))
        self.horizontalLayout_4.addWidget(self.formLoad_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.bscore_edit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.bscore_edit.setObjectName(_fromUtf8("bscore_edit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.bscore_edit)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.imscore_edit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.imscore_edit.setText(_fromUtf8(""))
        self.imscore_edit.setObjectName(_fromUtf8("imscore_edit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.imscore_edit)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.expscore_edit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.expscore_edit.setObjectName(_fromUtf8("expscore_edit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.expscore_edit)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_15)
        self.av_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.av_box.setObjectName(_fromUtf8("av_box"))
        self.av_box.addItem(_fromUtf8(""))
        self.av_box.addItem(_fromUtf8(""))
        self.av_box.addItem(_fromUtf8(""))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.av_box)
        self.ac_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.ac_box.setObjectName(_fromUtf8("ac_box"))
        self.ac_box.addItem(_fromUtf8(""))
        self.ac_box.addItem(_fromUtf8(""))
        self.ac_box.addItem(_fromUtf8(""))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.ac_box)
        self.auth_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.auth_box.setObjectName(_fromUtf8("auth_box"))
        self.auth_box.addItem(_fromUtf8(""))
        self.auth_box.addItem(_fromUtf8(""))
        self.auth_box.addItem(_fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.auth_box)
        self.conf_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.conf_box.setObjectName(_fromUtf8("conf_box"))
        self.conf_box.addItem(_fromUtf8(""))
        self.conf_box.addItem(_fromUtf8(""))
        self.conf_box.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.conf_box)
        self.int_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.int_box.setObjectName(_fromUtf8("int_box"))
        self.int_box.addItem(_fromUtf8(""))
        self.int_box.addItem(_fromUtf8(""))
        self.int_box.addItem(_fromUtf8(""))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.int_box)
        self.avail_box = QtGui.QComboBox(self.verticalLayoutWidget)
        self.avail_box.setObjectName(_fromUtf8("avail_box"))
        self.avail_box.addItem(_fromUtf8(""))
        self.avail_box.addItem(_fromUtf8(""))
        self.avail_box.addItem(_fromUtf8(""))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.avail_box)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.vulnName_edit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.vulnName_edit.setObjectName(_fromUtf8("vulnName_edit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.vulnName_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.clusterWidget.addTab(self.input_tab, _fromUtf8(""))
        self.validateWidget = QtGui.QTabWidget(TFG)
        self.validateWidget.setGeometry(QtCore.QRect(320, 20, 241, 231))
        self.validateWidget.setObjectName(_fromUtf8("validateWidget"))
        self.knn_tab = QtGui.QWidget()
        self.knn_tab.setObjectName(_fromUtf8("knn_tab"))
        self.horizontalLayoutWidget_12 = QtGui.QWidget(self.knn_tab)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_12.setObjectName(_fromUtf8("horizontalLayoutWidget_12"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget_12)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.knn_n_line = QtGui.QLineEdit(self.horizontalLayoutWidget_12)
        self.knn_n_line.setObjectName(_fromUtf8("knn_n_line"))
        self.horizontalLayout_11.addWidget(self.knn_n_line)
        self.knnbutton_3 = QtGui.QPushButton(self.knn_tab)
        self.knnbutton_3.setGeometry(QtCore.QRect(120, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.knnbutton_3.setFont(font)
        self.knnbutton_3.setObjectName(_fromUtf8("knnbutton_3"))
        self.validateWidget.addTab(self.knn_tab, _fromUtf8(""))
        self.svm_tab = QtGui.QWidget()
        self.svm_tab.setObjectName(_fromUtf8("svm_tab"))
        self.horizontalLayoutWidget_14 = QtGui.QWidget(self.svm_tab)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.horizontalLayoutWidget_14.setObjectName(_fromUtf8("horizontalLayoutWidget_14"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_14)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_13.addWidget(self.label_14)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.svm_kernel_box = QtGui.QComboBox(self.horizontalLayoutWidget_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.svm_kernel_box.sizePolicy().hasHeightForWidth())
        self.svm_kernel_box.setSizePolicy(sizePolicy)
        self.svm_kernel_box.setObjectName(_fromUtf8("svm_kernel_box"))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.svm_kernel_box.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.svm_kernel_box)
        self.horizontalLayoutWidget_16 = QtGui.QWidget(self.svm_tab)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(10, 100, 211, 71))
        self.horizontalLayoutWidget_16.setObjectName(_fromUtf8("horizontalLayoutWidget_16"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_16)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.svm_r_line = QtGui.QLineEdit(self.horizontalLayoutWidget_16)
        self.svm_r_line.setObjectName(_fromUtf8("svm_r_line"))
        self.horizontalLayout_15.addWidget(self.svm_r_line)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_16)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.svm_deg_line = QtGui.QLineEdit(self.horizontalLayoutWidget_16)
        self.svm_deg_line.setObjectName(_fromUtf8("svm_deg_line"))
        self.horizontalLayout_15.addWidget(self.svm_deg_line)
        self.horizontalLayoutWidget_17 = QtGui.QWidget(self.svm_tab)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 50, 211, 71))
        self.horizontalLayoutWidget_17.setObjectName(_fromUtf8("horizontalLayoutWidget_17"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_19 = QtGui.QLabel(self.horizontalLayoutWidget_17)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_16.addWidget(self.label_19)
        spacerItem5 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.svm_gamma_line = QtGui.QLineEdit(self.horizontalLayoutWidget_17)
        self.svm_gamma_line.setObjectName(_fromUtf8("svm_gamma_line"))
        self.horizontalLayout_16.addWidget(self.svm_gamma_line)
        self.svm_button = QtGui.QPushButton(self.svm_tab)
        self.svm_button.setGeometry(QtCore.QRect(120, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.svm_button.setFont(font)
        self.svm_button.setObjectName(_fromUtf8("svm_button"))
        self.validateWidget.addTab(self.svm_tab, _fromUtf8(""))
        self.years_tag = QtGui.QTabWidget(TFG)
        self.years_tag.setEnabled(True)
        self.years_tag.setGeometry(QtCore.QRect(580, 20, 161, 231))
        self.years_tag.setObjectName(_fromUtf8("years_tag"))
        self.train_years_tab = QtGui.QWidget()
        self.train_years_tab.setObjectName(_fromUtf8("train_years_tab"))
        self.gridLayoutWidget = QtGui.QWidget(self.train_years_tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 151, 201))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.years_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.years_layout.setObjectName(_fromUtf8("years_layout"))
        self.check2002 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2002.setObjectName(_fromUtf8("check2002"))
        self.years_layout.addWidget(self.check2002, 0, 0, 1, 1)
        self.check2003 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2003.setObjectName(_fromUtf8("check2003"))
        self.years_layout.addWidget(self.check2003, 1, 0, 1, 1)
        self.check2004 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2004.setObjectName(_fromUtf8("check2004"))
        self.years_layout.addWidget(self.check2004, 2, 0, 1, 1)
        self.check2005 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2005.setObjectName(_fromUtf8("check2005"))
        self.years_layout.addWidget(self.check2005, 3, 0, 1, 1)
        self.check2006 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2006.setObjectName(_fromUtf8("check2006"))
        self.years_layout.addWidget(self.check2006, 4, 0, 1, 1)
        self.check2007 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2007.setObjectName(_fromUtf8("check2007"))
        self.years_layout.addWidget(self.check2007, 5, 0, 1, 1)
        self.check2008 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2008.setObjectName(_fromUtf8("check2008"))
        self.years_layout.addWidget(self.check2008, 6, 0, 1, 1)
        self.check2009 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2009.setObjectName(_fromUtf8("check2009"))
        self.years_layout.addWidget(self.check2009, 7, 0, 1, 1)
        self.check2011 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2011.setObjectName(_fromUtf8("check2011"))
        self.years_layout.addWidget(self.check2011, 1, 1, 1, 1)
        self.check2010 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2010.setObjectName(_fromUtf8("check2010"))
        self.years_layout.addWidget(self.check2010, 0, 1, 1, 1)
        self.check2012 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2012.setObjectName(_fromUtf8("check2012"))
        self.years_layout.addWidget(self.check2012, 2, 1, 1, 1)
        self.check2013 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2013.setObjectName(_fromUtf8("check2013"))
        self.years_layout.addWidget(self.check2013, 3, 1, 1, 1)
        self.check2014 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2014.setObjectName(_fromUtf8("check2014"))
        self.years_layout.addWidget(self.check2014, 4, 1, 1, 1)
        self.check2015 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2015.setObjectName(_fromUtf8("check2015"))
        self.years_layout.addWidget(self.check2015, 5, 1, 1, 1)
        self.check2016 = QtGui.QCheckBox(self.gridLayoutWidget)
        self.check2016.setObjectName(_fromUtf8("check2016"))
        self.years_layout.addWidget(self.check2016, 6, 1, 1, 1)
        self.checkAllbutton = QtGui.QPushButton(self.gridLayoutWidget)
        self.checkAllbutton.setObjectName(_fromUtf8("checkAllbutton"))
        self.years_layout.addWidget(self.checkAllbutton, 7, 1, 1, 1)
        self.years_tag.addTab(self.train_years_tab, _fromUtf8(""))
        self.PCA_label = QtGui.QLabel(TFG)
        self.PCA_label.setGeometry(QtCore.QRect(350, 300, 201, 16))
        self.PCA_label.setObjectName(_fromUtf8("PCA_label"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(TFG)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(350, 290, 160, 80))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.pca_box_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.pca_box_layout.setObjectName(_fromUtf8("pca_box_layout"))
        self.pca_box = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.pca_box.setObjectName(_fromUtf8("pca_box"))
        self.pca_box_layout.addWidget(self.pca_box)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(TFG)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(470, 290, 235, 78))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.pca_data_layout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.pca_data_layout.setObjectName(_fromUtf8("pca_data_layout"))
        self.dimension_layout = QtGui.QHBoxLayout()
        self.dimension_layout.setObjectName(_fromUtf8("dimension_layout"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.dimension_layout.addWidget(self.label_2)
        self.dimension_edit = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.dimension_edit.setObjectName(_fromUtf8("dimension_edit"))
        self.dimension_layout.addWidget(self.dimension_edit)
        self.pca_data_layout.addLayout(self.dimension_layout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.threshold_edit_2 = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.threshold_edit_2.setText(_fromUtf8(""))
        self.threshold_edit_2.setObjectName(_fromUtf8("threshold_edit_2"))
        self.horizontalLayout.addWidget(self.threshold_edit_2)
        self.pca_data_layout.addLayout(self.horizontalLayout)

        self.retranslateUi(TFG)
        self.clusterWidget.setCurrentIndex(0)
        self.validateWidget.setCurrentIndex(0)
        self.years_tag.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TFG)

    def retranslateUi(self, TFG):
        TFG.setWindowTitle(_translate("TFG", "TFG - Informática", None))
        self.fileLoad_button.setText(_translate("TFG", "Load from file", None))
        self.label.setText(_translate("TFG", "Filename", None))
        self.formLoad_button.setText(_translate("TFG", "Load from form", None))
        self.label_5.setText(_translate("TFG", "Base Score", None))
        self.label_6.setText(_translate("TFG", "Impact Subscore", None))
        self.label_7.setText(_translate("TFG", "Exploitability subscore", None))
        self.label_8.setText(_translate("TFG", "Access vector", None))
        self.label_9.setText(_translate("TFG", "Access complexity", None))
        self.label_10.setText(_translate("TFG", "Authentification", None))
        self.label_11.setText(_translate("TFG", "Confidenciality impact", None))
        self.label_13.setText(_translate("TFG", "Integrity impact", None))
        self.label_15.setText(_translate("TFG", "Availability impact", None))
        self.av_box.setItemText(0, _translate("TFG", "Local access", None))
        self.av_box.setItemText(1, _translate("TFG", "Adjacent network", None))
        self.av_box.setItemText(2, _translate("TFG", "Network", None))
        self.ac_box.setItemText(0, _translate("TFG", "Low", None))
        self.ac_box.setItemText(1, _translate("TFG", "Medium", None))
        self.ac_box.setItemText(2, _translate("TFG", "High", None))
        self.auth_box.setItemText(0, _translate("TFG", "None required", None))
        self.auth_box.setItemText(1, _translate("TFG", "Requires single instance", None))
        self.auth_box.setItemText(2, _translate("TFG", "Requires multiple instances", None))
        self.conf_box.setItemText(0, _translate("TFG", "None", None))
        self.conf_box.setItemText(1, _translate("TFG", "Partial", None))
        self.conf_box.setItemText(2, _translate("TFG", "Complete", None))
        self.int_box.setItemText(0, _translate("TFG", "None", None))
        self.int_box.setItemText(1, _translate("TFG", "Partial", None))
        self.int_box.setItemText(2, _translate("TFG", "Complete", None))
        self.avail_box.setItemText(0, _translate("TFG", "None", None))
        self.avail_box.setItemText(1, _translate("TFG", "Partial", None))
        self.avail_box.setItemText(2, _translate("TFG", "Complete", None))
        self.label_3.setText(_translate("TFG", "Name", None))
        self.clusterWidget.setTabText(self.clusterWidget.indexOf(self.input_tab), _translate("TFG", "Input", None))
        self.label_12.setText(_translate("TFG", "No. of neighbors", None))
        self.knn_n_line.setText(_translate("TFG", "4", None))
        self.knnbutton_3.setText(_translate("TFG", "Train set \n"
" and clasify", None))
        self.validateWidget.setTabText(self.validateWidget.indexOf(self.knn_tab), _translate("TFG", "K-nn", None))
        self.label_14.setText(_translate("TFG", "Kernel", None))
        self.svm_kernel_box.setItemText(0, _translate("TFG", "rbf", None))
        self.svm_kernel_box.setItemText(1, _translate("TFG", "linear", None))
        self.svm_kernel_box.setItemText(2, _translate("TFG", "poly", None))
        self.svm_kernel_box.setItemText(3, _translate("TFG", "sigmoid", None))
        self.label_16.setText(_translate("TFG", "r", None))
        self.svm_r_line.setText(_translate("TFG", "0.0", None))
        self.label_17.setText(_translate("TFG", "degree", None))
        self.svm_deg_line.setText(_translate("TFG", "3", None))
        self.label_19.setText(_translate("TFG", "gamma", None))
        self.svm_gamma_line.setText(_translate("TFG", "0.125", None))
        self.svm_button.setText(_translate("TFG", "Train set \n"
" and clasify", None))
        self.validateWidget.setTabText(self.validateWidget.indexOf(self.svm_tab), _translate("TFG", "SVM", None))
        self.check2002.setText(_translate("TFG", "~2002", None))
        self.check2003.setText(_translate("TFG", "2003", None))
        self.check2004.setText(_translate("TFG", "2004", None))
        self.check2005.setText(_translate("TFG", "2005", None))
        self.check2006.setText(_translate("TFG", "2006", None))
        self.check2007.setText(_translate("TFG", "2007", None))
        self.check2008.setText(_translate("TFG", "2008", None))
        self.check2009.setText(_translate("TFG", "2009", None))
        self.check2011.setText(_translate("TFG", "2011", None))
        self.check2010.setText(_translate("TFG", "2010", None))
        self.check2012.setText(_translate("TFG", "2012", None))
        self.check2013.setText(_translate("TFG", "2013", None))
        self.check2014.setText(_translate("TFG", "2014", None))
        self.check2015.setText(_translate("TFG", "2015", None))
        self.check2016.setText(_translate("TFG", "2016", None))
        self.checkAllbutton.setText(_translate("TFG", "Check all", None))
        self.years_tag.setTabText(self.years_tag.indexOf(self.train_years_tab), _translate("TFG", "Train years", None))
        self.PCA_label.setText(_translate("TFG", "Principal Component Analysis", None))
        self.pca_box.setText(_translate("TFG", "Use PCA", None))
        self.label_2.setText(_translate("TFG", "Dimension:", None))
        self.label_4.setText(_translate("TFG", "Threshold:", None))

